### PR TITLE
Fixes and new feature. Need a bottle of wine after making the netlink work properly. :~

### PR DESCRIPTION
**Pull request by uskr**
- fix: reworked the netlink communication layer to properly handle endianness
- fix: reworked the netlink parsing
- feature: added --generate-channels argument to auto generate the wifi_interfaces sections with all supported channels

### CODE REVIEW

**Comment by uskr** [comment]
This PR mainly implements issue: [911](https://github.com/nzymedefense/nzyme/issues/911)

**Comment by uskr** [comment]
Will properly label/reference the issue on next PR's.

**Comment by lennartkoopmann** [comment]
Is this one ready for review?

**Comment by uskr** [comment]
No. Let me do this one properly. I will close this PR and will issue new ones with the issues.

**Pull request closed without merging**
