### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by lennartkoopmann**
Putting together some initial contributing guidelines for us and external contributors. What do you think @uskr?

### CODE REVIEW

**Comment by lennartkoopmann** [comment]
(for the record: This PR is already breaking some of those suggested guidelines :joy:)

**Comment by uskr** [comment]
Looks solid. During alpha, we will probably break the last requirement, the definition of "Done".

Mostly due to the nature of how dynamic the alpha process is (sometime we will implement something just to have the basic feature, but might refactor the whole thing before a stable release). So tests and documentation might get delayed.

But for the "normal" lifecycle, it looks like a concise but effective guideline.

One line has "Commit messages should be ", do you mean to have a ":" at the end of it, or did you not complete the statement?

**Review by uskr — COMMENTED** [review]
Like 26: "Commit messages should be ", did you not complete the sentence or is it just a ":" missing?

**Comment by lennartkoopmann** [comment]
> Like 26: "Commit messages should be ", did you not complete the sentence or is it just a ":" missing?

Ha, I think I got lost mid-thought here. :joy: Fixing.

**Comment by lennartkoopmann** [comment]
> Mostly due to the nature of how dynamic the alpha process is (sometime we will implement something just to have the basic feature, but might refactor the whole thing before a stable release). So tests and documentation might get delayed.

100% agree!

**Review by uskr — APPROVED** [review]

**Pull request merged**
