### PR TITLE
Implement issue #911 - added cli option -g/--generate-channels to auto generate config section with all supported wifi channels

### PR DESCRIPTION
**Pull request by uskr**
Implement issue #911
- bumped clap to 4.x
- added cli option -g/--generate-channels, this will generate the toml section with all wifi devices and all supported channels

### CODE REVIEW

**Comment by uskr** [comment]
Ready to review.

**Comment by uskr** [comment]
if the PR for issue 920 works, then I will have to redo this PR, so keep it on hold for now.

**Comment by uskr** [comment]
Ready for testing. I did not thoroughly tested this connected to a node, due to been out of town. But tap side looks ready for testing.

**Comment by lennartkoopmann** [comment]
(Waiting for PR #925 to be merged)

**Comment by uskr** [comment]
@lennartkoopmann if this one screams about the PR #925 dead code removal, let me know and I will do a final upstream merge and update this PR. But it should merge clean after 925 is done.

**Review by lennartkoopmann — COMMENTED** [review]
Can you update the `nzyme.conf.example` to reflect the new channel config syntax?

All the rest LGTM! :+1:

**Comment by lennartkoopmann** [comment]
I have added a note about this breaking change to #908

**Pull request merged**
